name: CI

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
      - name: Slack Notification
        uses: 8398a7/action-slack@v2
        with:
          status: custom
          payload: |
            {
              text: "${{job.status}}: Running <https://github.com/${{github.repository}}/commit/${{github.sha}}/checks|${{ github.action }}> on <https://github.com/${{github.repository}}/tree/${{github.ref}}|${{github.ref}}> by @${{github.actor}}",
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_CORE_DEV_ALERTS }}
        if: always() # Pick up events even if the job fails or is canceled.
