name: CI

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Download SDK
        run: $ANDROID_HOME/tools/bin/sdkmanager --install "system-images;android-29;default;x86"

      - name: Create
        run: echo no | $ANDROID_HOME/tools/bin/avdmanager create avd -n test -k "system-images;android-29;default;x86" -f

      - name: List
        run: $ANDROID_HOME/tools/bin/avdmanager list avd

      - name: Run
        run: $ANDROID_HOME/emulator/emulator -avd test