name: CI

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
      - name: Slack Notification
        uses: 8398a7/action-slack@v2
        with:
          status: custom
          payload: |
            {
              text: "${author.name} https://github.com/${owner}/${repo}/commit/${sha}|${sha} | https://github.com/${owner}/${repo}|${owner}/${repo} | https://github.com/${owner}/${repo}/commit/${sha}/action,
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_CORE_DEV_ALERTS }}
        if: always() # Pick up events even if the job fails or is canceled.
