name: CI

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
      - name: Test
        run: echo "${{ job.status }}"
      - name: Test2
        run: echo "${{ job.status == 'success' || 'no' }}"
