name: CI

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Create
        run: echo no | avdmanager create avd -n test -k "system-images;android-25;google_apis;armeabi-v7a" -f

      - name: List
        run: $ANDROID_HOME/tools/bin/avdmanager list avd

      - name: Run
        run: $ANDROID_HOME/emulator/emulator -avd test